### ISSUE TITLE
Free Plan Signup Flow

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#150]
**User Story**

AS A USER I want sign up to Keen Free plan without providing billings details so I could use the platform 

**Additional context**
- We need to re-define flow for free plan signup without providing billing details.
- The OAuth flows will require a "placeholder" page as we cannot pass plan details through Google / GitHub.

Story from the document:
5. As a user I want to sign up to the “Free” pricing plan not providing the Credit Card information. The configuration whether the CC is required or not should come from Chargify’s “require_credit_card” field of the product. Chargify reconfiguration and removal of “sign-up to product” flows is required before the implementation.

**Comment by gosiafelis** [comment]
**Submit buttons:**
- Change submit button copy in the 1st step to "Sign up to {plan_name} Plan" for the public plans. 
   Custom plans should still have 'Continue to billing'
- 2nd step submit button copy should be 'Complete sign up'

**Plan selection:**
- In the 2nd it should be not possible to change the plan. We can use the 'custom offer' component in the second step instead of the select.

**Updated flow:**
https://invis.io/FPWCGOEWMKJ#/408670504_Signup-New-Pricing-Flow
